export const FETCH_CONTACTS = "FETCH_CONTACTS";
export const ADD_CONTACT = "ADD_CONTACT";

export const FETCH_CONTACT_DETAIL = "FETCH_CONTACT_DETAIL";

export const SEARCH_CONTACT = "SEARCH_CONTACT";

export const DELETE_CONTACT = "DELETE_CONTACT";

export const UPDATE_CONTACT = "UPDATE_CONTACT";
